name: iot-fiware

services:
  line-server:
    build: ./line-server
    container_name: iot-fiware-line-server
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - .env
    volumes:
      - photos:/app/photos
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - fiware-base-net
      - default

volumes:
  photos:
    external: true
    name: line_picarx_photos

networks:
  fiware-base-net:
    external: true
    name: fiware-base-net
